### ISSUE TITLE
Documentation tidy up, and information on setting up PDO

### ISSUE THREAD

**Issue by halkyon** [silverstripe/silverstripe-mssql#19]
Currently the documentation in this module still refers to FreeTDS and the `mssql_*()` functions, but that's been replaced with PDO, this needs to be updated to reflect the changes that were made.

Also `_register_database.php` in this module is currently checking for "sqlsrv" driver. When using PDO from *nix and connecting to MSSQL, I believe it uses a different driver. That needs to be validated as part of rewriting the documentation.

Note that the class docs for `MSSQLDatabase.php` contain some documentation. That should be moved entirely into the `README.md` file, or put into a `docs` folder, whatever makes sense.

Note: This only applies to the latest changes in master, not the 3.1 compatibility branch.

**Comment by ColmMcBarron** [comment]
Bump, any update on this documentation?
