### ISSUE TITLE
1.0 (master) doesn't work on linux anymore

### ISSUE THREAD

**Issue by xini** [silverstripe/silverstripe-mssql#32]
I have a project where SS is installed on linux and I need to connect to a MSSQL database to write some data into an external system.
With SS <= 3.1 and this module in version 0.9 it worked, because https://github.com/silverstripe/silverstripe-mssql/blob/0.9.7/code/MSSQLDatabase.php#L125 checked which library was available. https://github.com/silverstripe/silverstripe-mssql/blob/master/code/MSSQLDatabaseConfigurationHelper.php and https://github.com/silverstripe/silverstripe-mssql/blob/master/code/SQLServerConnector.php#L62 now use sqlsrv for all connections. sqlsrv is only available for Windows.
Does anyone have a solution for this scenario?

**Comment by dhensby** [comment]
Can you try using the PDO connector instead (SS 3.2+) `MSSQLPDODatabase`?

**Comment by tractorcow** [comment]
Unfortunately mssql driver is no longer actively maintained for php, and we are dropping support for it. Additionally, it has no support for parameterised queries, so it's not ideal for us to promote it as a robust backend.

As @dhensby suggested, you are probably better of trying to use PDO in this case.

**Comment by xini** [comment]
Sorry, I haven't had time to try this. I'll let you know if I run into problems. Thanks!

**Comment by xini** [comment]
I had a chance to look into this. 
The configuration helper uses the 'sqlsrv' driver for all connections, no matter what operating system it is running on (see https://github.com/silverstripe/silverstripe-mssql/blob/master/code/MSSQLDatabaseConfigurationHelper.php#L69). On Linux, the PDO extension used is not 'sqlsrv', but 'dblib'. 
So, also with PDO, we need to distinguish between operating systems. 
With dblib, the connection needs to be estabished as follows:
```
$conn = new PDO("dblib:host=$host:$port;dbname=$db", $username, $password);
```

**Comment by dhensby** [comment]
@tractorcow looks like an issue?

**Comment by tractorcow** [comment]
You're looking at the master branch, which isn't 1.0.

I'm fixing this anyway. :D

**Comment by xini** [comment]
doesn't matter. same issue.

**Comment by tractorcow** [comment]
@xini I've done a bit of minimal work to get dblib supported in core at https://github.com/silverstripe/silverstripe-framework/pull/5996

**Comment by xini** [comment]
Thanks. I'll see what I can do. Not urgent for me at the moment as I'm just using plain PDO at the moment to write my data.
