### ISSUE TITLE
SilverStripe\MSSQL\MSSQLDatabaseConfigurationHelper' not found

### ISSUE THREAD

**Issue by ghost** [silverstripe/silverstripe-mssql#44]
I get this error when trying to use the mssql. I have no clue why the file is in the code folder.

**Comment by NightJar** [comment]
Hi, <user account that has been deleted>

I believe this was resolved with #47 (specifically [this line](https://github.com/silverstripe/silverstripe-mssql/pull/47/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R4)), and it's most likely that you were testing against the misguided stable tag 2.0.0, which likely fell between autoloaders (being declared PSR4 but not being in the `vendor` folder).

Do you mind if this is closed?
