### ISSUE TITLE
Get indexes working with new index spec in 4.x

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-mssql#45]
see https://github.com/silverstripe/silverstripe-framework/pull/6930

**Comment by kinglozzer** [comment]
Still an issue, related PRs from other drivers to use for inspiration:

- https://github.com/silverstripe/silverstripe-sqlite3/pull/35/
- https://github.com/silverstripe/silverstripe-postgresql/pull/68/

**Comment by kinglozzer** [comment]
Fixed in #51
